services:
    report_runner:
        class: GepurIt\ReportBundle\ConsoleCommand\RunReportGeneratorCommand
        arguments:
            - "@logger"
            - '@report.rabbit_helper'
            - '%kernel.project_dir%'
        tags:
           - { name: 'console.command' }

    report_listener:
        class: GepurIt\ReportBundle\ConsoleCommand\ExecuteReportGeneratorCommand
        arguments:
            - '@report_handler'
            - '@doctrine.odm.mongodb.document_manager'
            - '@logger'
        tags:
            - { name: 'console.command' }
