services:
    data_types.datatime:
        class: GepurIt\ReportBundle\ReportType\ReportDataTypes\DateTime
        tags:
            - { name: 'report_data_type' }

    data_types.date:
        class: GepurIt\ReportBundle\ReportType\ReportDataTypes\Date
        tags:
            - { name: 'report_data_type' }

    data_types.boolean:
        class: GepurIt\ReportBundle\ReportType\ReportDataTypes\Boolean
        tags:
            - { name: 'report_data_type' }

    data_types.string:
        class: GepurIt\ReportBundle\ReportType\ReportDataTypes\StringData
        tags:
            - { name: 'report_data_type' }

    data_types.integer:
        class: GepurIt\ReportBundle\ReportType\ReportDataTypes\Integer
        tags:
            - { name: 'report_data_type' }
