imports:
    - { resource: console_commands.yml}
    - { resource: report_data_types.yml}

services:
    report.rabbit_helper:
        class: GepurIt\ReportBundle\ReportCommandHandler\RabbitHelper
        arguments:
            - '@rabbit_mq'

    ReportBundle\ReportCommandHandler\ReportCommandHandler:
        class: GepurIt\ReportBundle\ReportCommandHandler\ReportCommandHandler
        arguments:
             - '@doctrine.odm.mongodb.document_manager'
             - '@logger'
             - '@report.rabbit_helper'
        public: true

    report_handler:
        alias: GepurIt\ReportBundle\ReportCommandHandler\ReportCommandHandler

    report.type_guard:
        class: GepurIt\ReportBundle\ReportType\ReportTypeGuard
        arguments:
             - '@security.token_storage'
             - '@app.access.decision_manager'
        public: true

    report.type_registry:
        class: GepurIt\ReportBundle\ReportType\ReportTypeRegistry
        public: true

    report.data_type_registry:
        class: GepurIt\ReportBundle\ReportType\ReportDataTypeRegistry
        public: true

    report.command_request_factory:
        class: GepurIt\ReportBundle\CreateCommand\ReportCommandRequestFactory
        public: true
        arguments:
            - '@report.data_type_registry'
            - '@property_accessor'

    helper.date:
        class: ReportBundle\Helpers\DateHelper